### ISSUE TITLE
OGS API Error

### ISSUE THREAD

**Issue by alexmitrani** [acristescu/OnlineGo#106]
This error message started appearing about 5 minutes ago.  

![Screenshot_20210427-120110](https://user-images.githubusercontent.com/27974470/116274343-942afe80-a750-11eb-8f15-0effe8735998.png)

Thanks

Alex

**Comment by acristescu** [comment]
this looks like a duplicate of #105 . Can you please update the app?

**Comment by alexmitrani** [comment]
Yes, I closed the issue because I updated the app and it seems to have been fixed.  Thanks.
