### ISSUE TITLE
Separate notifications for live vs correspondence games

### ISSUE THREAD

**Issue by marshmn** [acristescu/OnlineGo#107]
Currently a notification is received when a game ends - regardless of the type of game, whether it is live or correspondence. This means that when playing live games in a web browser, I still get notifications on my mobile device when that game ends.

I use the mobile app only for correspondence games and as such I only care about notifications for correspondence games in the app.

It would be good to separate the notifications so that you can enable/disable them independently for correspondence games and live games.

**Comment by acristescu** [comment]
Implemented by @bqv
