### ISSUE TITLE
KataGo stuck on "I'm thinking..." after back button

### ISSUE THREAD

**Issue by MatthewScholefield** [acristescu/OnlineGo#110]
Steps to reproduce:
 - Click "Offline AI" from main view
 - Click Android's back button (for me a back gesture) to go back to main view
 - Click "Offline AI" again
 - Make any move

Expected: AI responds
Actual: AI stuck at "I'm thinking..."

Let me know if you can reproduce or if I should add more details.

**Comment by MatthewScholefield** [comment]
Just edited the title/description to include steps to reproduce.

**Comment by MisterFruits** [comment]
Same behaviour here (no gesture, using back button)

**Comment by MatthewScholefield** [comment]
Btw, just to make it clear in case it wasn't, the simple workaround is restarting the app and directly clicking "Offline AI" > "New Game".

**Comment by acristescu** [comment]
Thank you for the reports. Could you guys let me know what phones you are using? I could not reproduce this on Samsung s9+ or s21 Ultra.

**Comment by MatthewScholefield** [comment]
Hmm. I'm on a Oneplus 8T on Android 11. [Here's a video for illustration](https://gofile.io/d/fWlSoD). Also I tried disabling gestures and just using a navbar and the behavior is the same for me.

**Comment by acristescu** [comment]
wow, great video demonstration, sounds like you're in the business of mobile development? :) Gestures vs navbar would not influence it, what happens behind the scenes is that I start the katago binary and use local sockets to connect to it. Somehow the katago process gets killed and not restarted, I'll have to figure out why.

**Comment by acristescu** [comment]
Managed to reproduce it and fix it, the fix will be available in the next version. Thank you for the great report both of you!
