### ISSUE TITLE
Bug: irregular board size (19x9) presented as 19x19 in app

### ISSUE THREAD

**Issue by alexmitrani** [acristescu/OnlineGo#114]
This game was created as 19 x 9 by accident.  
https://online-go.com/game/37696518

![Screenshot_20211011-155325-807.png](https://user-images.githubusercontent.com/27974470/136840151-097ae6a1-adea-4b91-a240-04372b0005f1.png)

In the app it looks like a regular 19 x 19 board.  

![Screenshot_20211011-155344.png](https://user-images.githubusercontent.com/27974470/136840474-a1028235-4055-424d-a5b9-b7488e82dd4d.png)

Maybe the app doesn't support non-standard board sizes, and if this is the case maybe they shouldn't appear at all, or there could be a message.  

The bug is that the board dimensions in the app are inconsistent with those on the server.

Thanks

Alex

**Comment by acristescu** [comment]
Fixed in 389
