### ISSUE TITLE
"My turn" games no longer sorted by how much time I have left

### ISSUE THREAD

**Issue by EgMan** [acristescu/OnlineGo#115]
This is how games used to be sorted before the Material UI update.  Now, I can't tell what metric (if any) they are sorted by.  This is annoying because I have to search through all my games to prioritize which moves need to be made, rather than just looking at the top of the list.  

Please fix this, or at least provide a settings option to sort by time left to move.  

Thank you

**Comment by acristescu** [comment]
Fixed in build 389
