### ISSUE TITLE
Wrong stone color in recently finished

### ISSUE THREAD

**Issue by sdrenn** [acristescu/OnlineGo#116]
In version alpha_b382 on Android I have an issue: color of stone (one small round thing) in recently finished games, that, I assume, represents my stone color, in fact, represents stone color of my opponent.

Is that on purpose? In older versions color line has my color, so I figured, it could be a bug.

**Comment by acristescu** [comment]
Thanks for the report, but It's not a bug, I figured since I have the name of the opponent right there it should be a the colour of the opponent too...
