### ISSUE TITLE
Chat shows opponent's private notes

### ISSUE THREAD

**Issue by MisterFruits** [acristescu/OnlineGo#122]
I could see the private note of my opponent during the game:

![Screenshot_2021-12-19-07-03-01-552_io zenandroid onlinego](https://user-images.githubusercontent.com/6260699/146683682-8221ceb7-a30e-4355-87da-14c0df74d562.jpg)

That's not the case on the online go chat:
![Screenshot_2021-12-19-07-02-38-724_com android chrome](https://user-images.githubusercontent.com/6260699/146683708-a5567187-d024-4e0f-8df1-3ca96bb53a43.jpg)

**Comment by thouis** [comment]
Seeing this as well.

**Comment by acristescu** [comment]
Fixed in alpha_b396
