### ISSUE TITLE
Play against AI broken after upgrading

### ISSUE THREAD

**Issue by MatthewScholefield** [acristescu/OnlineGo#123]
After upgrading to `alpha_b389`, whenever I click the "Play Against AI" button it loads forever saying it's setting things up. However, I cleared the cache and data and now it works.

Just wanted to make this issue for visibility in case anyone else runs into the problem.

**Comment by acristescu** [comment]
Fixed in aplha_b401, I know I'm very late to the party, the way to work around it before this fix was to delete the data and restart the app @MatthewScholefield
