### ISSUE TITLE
"illegal Ko move" spam on analysis mode

### ISSUE THREAD

**Issue by popz73** [acristescu/OnlineGo#125]
Hi Alex, 
This bug is probably linked to the new update to game logic/analysis mode, there's occasions where "illegal Ko move" error is spammed in positions that have nothing to do with a Ko..
Below an example:
![Screenshot_20220327-101838](https://user-images.githubusercontent.com/12851952/160275072-cceef66c-a6dc-4d24-866f-86d42b56d0af.png)
I'm trying to place move 15 on D12, but the app doesn't let me (toast with the error on the bottom).

**Comment by acristescu** [comment]
Fixed in the next version. It happens when you navigate back exactly 2 moves at the end of a variation and then try to replay the exact same moves.
