### ISSUE TITLE
Issue with rank calculation for dan ranks.  

### ISSUE THREAD

**Issue by alexmitrani** [acristescu/OnlineGo#126]
The dan ranks calculated by the app seem to be 1.0 higher than those displayed on the OGS website.  For instance: 

![Screenshot_20220606-174755-896](https://user-images.githubusercontent.com/27974470/172262707-1e3c968d-c14c-4b68-9033-305430ffed4f.png)

My rank is 1.0 dan on OGS.  In the app it is incorrectly shown as 2.0 dan: 

![Screenshot_20220606-185852-719](https://user-images.githubusercontent.com/27974470/172262886-3a837cc8-b8c5-4c86-ab18-edac9d06cfcf.png)

Thanks.

**Comment by acristescu** [comment]
Thank you for the report and sorry for the slow response. It is fixed in the next version alpha_b465.

**Comment by alexmitrani** [comment]
Thanks very much.
