### ISSUE TITLE
Bad layout on Fold 3 large screen

### ISSUE THREAD

**Issue by littlediobolic** [acristescu/OnlineGo#131]
I know it's a pretty niche issue, but using the Galaxy Fold 3's big 4:3 screen produces some weird layout issues / bugs. Here are some pictures for an example:

VS another player in portrait mode is unusable, as the game detail elements are all over the board
![Screenshot_20221122_210925_Online Go.jpg](https://user-images.githubusercontent.com/1341157/203457059-74cbbe69-054f-49b1-bcce-1fd4d78983ff.jpg)

Landscape mode is pretty much good, but the username text seems to be too big
![Screenshot_20221122_210937_Online Go.jpg](https://user-images.githubusercontent.com/1341157/203457103-66fa05a6-e057-463d-8725-a12be79d7593.jpg)

In the KataGo screen, the board doesn't not fit in either
![Screenshot_20221122_211009_Online Go.jpg](https://user-images.githubusercontent.com/1341157/203457175-3c27292e-f69e-4141-8520-2318e31de0be.jpg)
![Screenshot_20221122_211019_Online Go.jpg](https://user-images.githubusercontent.com/1341157/203457183-c71067e1-d6e9-445a-9c78-ff045ba2b105.jpg)

I'm on the latest version alpha_b481

**Comment by acristescu** [comment]
@littlediobolic thank you for the report, that is indeed quite unacceptable. I will prioritise this.

**Comment by littlediobolic** [comment]
Sure thing! I'm pretty used to it tbh, most apps don't layout on Fold devices properly 😅 I only submitted the issue because it looks like the newest UI update is what caused the portrait board to be unusable. Peviously I could pretty much just see the board, but I could use it lol.

**Comment by acristescu** [comment]
Sorry for the delay, I did get around to having a look today. It's still a massive waste of space, but at least it's usable. I'll have to figure out a better layout for "almost square" devices, feel free to suggest something.

![Screenshot_1672852270](https://user-images.githubusercontent.com/2835035/210611254-cae844c7-dfdc-4054-b153-83bcb964918d.png)

**Comment by acristescu** [comment]
Fixed in v503

**Comment by littlediobolic** [comment]
This is awesome! Thanks for the fix! It's completely usable, so no complaints from me lol.
