### ISSUE TITLE
Setting for Keep screen on

### ISSUE THREAD

**Issue by RuthAlk** [acristescu/OnlineGo#137]
It would be nice if the app had a setting to keep the screen on. 

If I look at the board for a while without touching my phone, it automatically turns off. I could disable this for the whole phone, but would then have to turn it back on later, which is a bit of a hassle.

**Comment by MathieuDreano** [comment]
Good idea, seems like something we can work on.
https://developer.android.com/training/scheduling/wakelock

**Comment by acristescu** [comment]
A good idea, so long as two conditions are met:

1. it only happens on the game screen
2. the behaviour can be disabled in the settings (but defaults to enabled)

**Comment by acristescu** [comment]
Implemented by @kpe
