### ISSUE TITLE
[Feature requests] Move-confirmation in "play against AI" 

### ISSUE THREAD

**Issue by Curious-r** [acristescu/OnlineGo#139]
Could you please add an option to enable move-confirmation when we play against AI?
The screen of cellphone is so cramped.. It is very easy to make a wrong move.

**Comment by acristescu** [comment]
Hey man thanks for getting in touch. The reason this feature is not there it's because against the AI you can always just take the move back if you made a mistake, no harm done... the AI doesn't mind :)

**Comment by Curious-r** [comment]
> Hey man thanks for getting in touch. The reason this feature is not there it's because against the AI you can always just take the move back if you made a mistake, no harm done... the AI doesn't mind :)

Copy that, thanks for reply😸
