### ISSUE TITLE
Support LGBTQ+ and Pirate flags

### ISSUE THREAD

**Issue by benjaminpjones** [acristescu/OnlineGo#149]
OGS supports a variety of flags that aren't associated with nationality.  Two of these are supported by emoji: 🏴‍☠️ & 🏳️‍🌈

<img width="116" alt="Screen Shot 2023-02-15 at 6 17 47 AM" src="https://user-images.githubusercontent.com/25233703/218865969-b9220317-2f17-4aca-b77b-8f8383f193b1.png">

I'm proposing to add the following mappings to `convertCountryCodeToEmojiFlag()`:
- `_LGBT` -> 🏳️‍🌈
    - Note: OGS shows the "Progress Pride" flag, so it isn't an exact match, but I figure pretty close for an emoji
- `_Pirate` -> 🏴‍☠️

Please assign me if it's okay to implement, I'm basically looking for a "good first issue" here 😁

**Comment by acristescu** [comment]
LGBT is a good idea, not sure about the other stuff there. Feel free to implement if you're so inclined!
