### ISSUE TITLE
Tally percentages should be "not applicable" when there are zero games

### ISSUE THREAD

**Issue by alexmitrani** [acristescu/OnlineGo#152]
Currently one of them shows as 1000% and the other as 100%. 

![Screenshot_20230307-080009-566.png](https://user-images.githubusercontent.com/27974470/223404174-5524f19b-584a-49f6-941d-ceea68623031.png)

They should probably be NA or "-" when there are zero games.  

Thanks.

**Comment by acristescu** [comment]
Thanks for the report, I made them all 0% for the next version.
