### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by acristescu** [acristescu/OnlineGo#16]
Notification customisation?

**Comment by hadim** [comment]
Disable move confirmation when playing?

**Comment by heikoherold** [comment]
> Notification customisation?

That will be one of the first thing new users will look for and be disappointed if it isn't there, so Yes Please. Advanced users will go into the Android OS Notification dialog but most probably don't know how to change it there.
Providing a default stone-on-board sound would be a nice touch, or a sound repeated a couple of times.

**Comment by acristescu** [comment]
Implemented a new settings page allowing for some notification customisation via the phone's settings. Merged in `alpha_b186`
