### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by cornetth** [acristescu/OnlineGo#22]
I would like a dark/night theme like on web page. Light text on a dark/black background. Not exactly an issue. More of a wish. :-)

**Comment by acristescu** [comment]
Thank you for the suggestion. If enough people ask for it I will try, but it's a big investment in time as I am no designer :)

**Comment by heikoherold** [comment]
I second this.
An easy fast first step would be:

- invert luminosity for every white/gray surface and text (light gray becomes dark gray, dark gray text becomes light gray text).
- Exchange the white-on-light blue in the Top bar (title/chat/waiting games) with white-on-dark blue
- Keep board and stones as is.
- Keep every other color as is.

Would probably need some tweaking in the light levels, dark gray text on light gray surface is more readable than light gray text on dark surface, unless light levels or font thickness is altered; but for a first try with minimal effort and big gain? Go for it.

Also much later the board could be changed to something like dark brown oak with white grid lines (can't be too dark or your black stones won't be as visible). But that can wait for step 2.

**Comment by kirang89** [comment]
I'd like this as well :)

**Comment by acristescu** [comment]
Believe it or not, this is a most requested feature, even if there are some (IMHO) glaring ommisions in the currently released app, such as the inability to challenge somebody, the inability to respond to challenges or the fact that the game does not recognize even basic KOs.

But vox populi, vox dei, so I'll try to find some time this christmas and see what I can do.

**Comment by heikoherold** [comment]
> Believe it or not, this is a most requested feature, even if there are some (IMHO) glaring ommisions in 

I believe it because it is quite easy to notice, especially if you play in the evening in a darkish environment. So I commented on it, too. However we are not paying customers or a insurrection-willing (able) mob so no vox dei, it all depends on your graciousness 😆 

OTOH operative missing features are quite important, especially responding to challenges (even: just seeing there is a challenge). It depends how much time you can raise and how much time any single feature needs before a first push is feasible 😄

**Comment by popz73** [comment]
Hi Alex,
I will take up dark mode this week if you're ok with it. Will follow the general ideas described in https://developer.android.com/guide/topics/ui/look-and-feel/darktheme

**Comment by acristescu** [comment]
Oh wow, you're a braver soul than me then :) Thank you for offering to help. Please feel free to go ahead with that so long as you're OK with me later tweaking the shades of the dark colors to match my artistic sense (if you could call it that). I would like it to look something like what the Outlook app does (for both light and dark modes), but I am open to discussion on the exact shades of the colors.

Please be aware of the following:
- this might sound simple, but it's actually not because Android and theming is a nightmare...
- there is a stale branch from 4 months ago in which I looked at `<item name="android:forceDarkAllowed">true</item>`. I wasn't quite happy with the result, but if you're interested in going that direction (and I don't recommend it) you can have a look at that branch for some inspiration (it's called `dark-mode`).
- those features are only available in API 29, please make sure we're not breaking things for people that are using older APIs (you'll need to test on both a new and an old emulator).
- I think we should have a toggle for the dark mode that has 3 states (as described in that link you posted): light, dark and either "system default" or "set by battery saver" depending on the Android version.

*Please pull the code before you start as I have made some big changes (introduced Dependency Injection)*

**Comment by alexmitrani** [comment]
I would also appreciate a dark theme, just adding my vote 🙂

**Comment by popz73** [comment]
wip:
![test](https://user-images.githubusercontent.com/12851952/82731487-9ea27400-9d07-11ea-86a2-f5346f971cee.jpeg)
@acristescu something in this vibe?

**Comment by acristescu** [comment]
Hey @popz73 , that looks great for a WIP, thank you very much for looking into this! You're probably already on this, but I would mention that we could improve this by basically increasing the contrast between the text and the background a little, mostly by making the text "whiter". Please see the screenshots below (from Outlook) for reference. Notice how they are using several shades of white for the text but they are all whiter than our one.

Secondly, we need to have a more obvious indicator for the currently selected item in the navigation bar at the bottom. Outlook is using a filled icon (which is a luxury we can't afford unless we find a decent graphical artist to help) so we must figure something out. Perhaps pure white tint, or bold, or both?

I like that you changed the shade of blue, as the default color definitely did not work on a dark background, however I feel that this particular shade has a bit too much green in it. I quite like the blue that Outlook is using for their Floating Action Button. Can we try that one and see how it looks?

But all in all I like how it all looks, you've gotten a better result than what I have on that stale branch!

Here are a few screenshots from the outlook app (yes, the calendar looks distinctly empty, goddamn quarantine):

![image](https://user-images.githubusercontent.com/2835035/82732468-4ff3da80-9d05-11ea-96a4-6d0853d6559f.png)
![image](https://user-images.githubusercontent.com/2835035/82732478-5aae6f80-9d05-11ea-8c8d-0739823ac677.png)
![image](https://user-images.githubusercontent.com/2835035/82732480-613ce700-9d05-11ea-914e-28ea7658ed6a.png)

**Comment by popz73** [comment]
thanks for the suggestions! yup, that higher contrast looks much better - I was using Outlook _desktop_ dark mode as basis :) - but the mobile higher-contrast palette is indeed nicer.
I'll also put the title bar lighter than the background. will share more pics once I get around the rest of the screens

**Comment by popz73** [comment]
wip v2, with almost every screen converted. except for that damn player chip :) 
thoughts?
![photo5929520175869178448](https://user-images.githubusercontent.com/12851952/82739592-eee9f800-9d40-11ea-8721-0f8cf5d8aefc.jpg)
![photo5929520175869178450(1)](https://user-images.githubusercontent.com/12851952/82739594-f3aeac00-9d40-11ea-88d3-7cfb6f820a44.jpg)
![photo5929520175869178452](https://user-images.githubusercontent.com/12851952/82739597-f5786f80-9d40-11ea-8264-d5772a82f008.jpg)
![photo5929520175869178447](https://user-images.githubusercontent.com/12851952/82739598-f7dac980-9d40-11ea-915e-0cc89fc811b8.jpg)
![photo5929520175869178451](https://user-images.githubusercontent.com/12851952/82739599-fad5ba00-9d40-11ea-8fda-f8745367a1df.jpg)
![photo5929520175869178446](https://user-images.githubusercontent.com/12851952/82739601-fc9f7d80-9d40-11ea-868f-9c947f370151.jpg)
![photo5929520175869178445](https://user-images.githubusercontent.com/12851952/82739603-ff01d780-9d40-11ea-9252-3b342bff96f0.jpg)

**Comment by acristescu** [comment]
Uuu... that definitely looks very nice to my eyes. Mind you I never use dark mode so maybe we should get more opinions? There are only a few minor things that I would tweak:

- there is still no indication of which item in the bottom navigation bar is selected.
- the status bar looks a bit jarring with that blue, in most dark mode apps I've seen they are set to a dark colour, perhaps the same one as the app bar (like in outlook or the one below).
- the "No OGS account..." label should be some manner of white or grey as well IMHO

Also, there are a few things that probably need some discussing:
- what issues are you encountering with the chips? is there anything I can help with?
- the entire board looks quite bright on the dark background, maybe we should consider changing the look and feel of that too? I know that's a whole different beast, just wanted to see what you think about it...

![image](https://user-images.githubusercontent.com/2835035/82740504-37a1b100-9d41-11ea-9cad-8f9abda038f2.png)

**Comment by popz73** [comment]
>     * there is still no indication of which item in the bottom navigation bar is selected.
This is already a problem in the Light mode - apart from the "circle" when we press it, there isn't any indication. I'd do it in a separate PR

>     * the status bar looks a bit jarring with that blue, in most dark mode apps I've seen they are set to a dark colour, perhaps the same one as the app bar (like in outlook or the one below).
hah - didn't even know that color was set by us :P sure I'll change it


>     * the "No OGS account..." label should be some manner of white or grey as well IMHO
ok

 
> Also, there are a few things that probably need some discussing:
> 
>     * what issues are you encountering with the chips? is there anything I can help with?
no problem, just noticed them when taking the screenshots - they're ok now

 
>     * the entire board looks quite bright on the dark background, maybe we should consider changing the look and feel of that too? I know that's a whole different beast, just wanted to see what you think about it...

good thing you mention it :) I did change it in the meantime. Dark mode has a slightly warmer/darker texture - not too much to avoid making it too different, but definitely enough to not be bright on the eyes.

![texture](https://user-images.githubusercontent.com/12851952/82740661-48572480-9d4b-11ea-9bb2-98e35acdc5eb.png)
![texture_dark](https://user-images.githubusercontent.com/12851952/82740662-48efbb00-9d4b-11ea-9e91-3ac444a9a483.png)
