### ISSUE TITLE
[Feature request] Jump 10 moves at a time and at beginning/end of game

### ISSUE THREAD

**Issue by d-korni** [acristescu/OnlineGo#3]
Now that we can see past games and go through the moves, it would be really useful to have an option to move more moves back and ahead, rather than the one move jump.

This can perhaps be done with additional buttons, or by long pressing/double taping the existing arrow buttons (so as not to have too many buttons).

**Comment by acristescu** [comment]
This is a case where I failed at communicating the feature... it's already there, you just have to hold the button down :) If you do, for the first 10 moves it goes slowly, for the next 20 faster and then very, very fast... The timings could be tweaked, but it takes only a few seconds to rewind a full 19x19 game...

**Comment by d-korni** [comment]
I tried it before posting, but it seems I wasn't patient enough. Works indeed as you suggest!
