### ISSUE TITLE
Support "Undo last move"

### ISSUE THREAD

**Issue by MielsvS** [acristescu/OnlineGo#31]
On the website you're able to undo a move
this results in a question to the opponent, stating that the other player has requested an undo of the last move. Which you can accept.
If you choose not to accept you can just do your next move (thus declining the request)

The app doesn't have the "undo" button.
But (perhaps more important): it doesn't support the "accept undo request" option (nor inform you on it).

Rationale:
As a result a player can feel offended: if a (novice) friend is using the undo button on a regular basis it seems like I'm ignoring him all the time. But I'm not even aware he's requesting undos!

Options:
- implement entire "undo last move" user story
if that's too much:
- show "Accept undo last move request"
or
- automated text in the chat stating that user A has requested an undo but user B is using an app that doesn't support this feature. "If needed you can accept the undo on the full site version at online-go.com" or something like that.

**Comment by acristescu** [comment]
Partially implemented in v145. The flow of accepting an undo is implemented, the flow for requesting one is still in TODO.

**Comment by acristescu** [comment]
Implemented in today's version 225

**Comment by popz73** [comment]
sweeeet

**Comment by popz73** [comment]
hi @acristescu , 
It's very easy to tap the new Undo button (that is now on the "pass" button) by mistake... and unlike the pass button, there's no confirmation dialog, it requests an undo instantly and it's also impossible to cancel afterwards :/
I know that the button in OGS website doesn't have a confirmation dialog either, but that one is not at all so easy to hit.

Are you ok with adding a confirmation dialog, just like the Pass one has?

**Comment by acristescu** [comment]
I did consider if that should be the case... I decided against it because, as you said, the website doesn't have one and the effect if you do click it by mistake is not so big as if you are passing. But perhaps you are right maybe we should add it...

**Comment by popz73** [comment]
I can do a PR for it, it's a nice simple one for me to rebuild the project
and get back into contributing

**Comment by acristescu** [comment]
That sounds great, please feel free to do it. You can of course use the pass button as an example of how to do this properly.

As a side note, if you're interested in contributing, please be aware that the most recent stuff (such as the Joseki Explorer) is done using the MVI architecture, which might be a bit hard to wrap your head around if you're not familiar with it (I know I definitely struggled).

**Comment by acristescu** [comment]
@popz73 Don't want to be pushy, but are you still interested in this? People are indeed complaining about the feature missing...

**Comment by popz73** [comment]
No prob, feel free to add it yourself in case the priority is getting high,
there is plenty other small things I can contribute once I get back to
building the project
