### ISSUE TITLE
[Feature Request] Board coordinates

### ISSUE THREAD

**Issue by heikoherold** [acristescu/OnlineGo#37]
Either an option, or overlay when the board border is long pressed? Space is tight I know :worried:

Jumping out to the website anytime somebody tells you about that move on Q12 (or you want to say something) isn't nice. Maybe by practice it will get more easy after getting better at the game :laughing:

**Comment by popz73** [comment]
I could take this one. Idea would be to add a toggle in the settings, all-so-slightly increasing borders to fit the space for 4-way small coordinates, mimicking what the toggle of the Pandanet app is doing:
<img src="https://user-images.githubusercontent.com/12851952/50384497-b7979780-06c5-11e9-8133-2ddc154c2509.png" width="400">
<img src="https://user-images.githubusercontent.com/12851952/50384501-c3835980-06c5-11e9-88cf-3cca330f340f.png" width="400">

**Comment by heikoherold** [comment]
You realize "increasing the border" means "reducing everything slightly" because we are on mobile with fixed-sized screen, all used up. 
That's the reason I suggested an overlay on long press on the border or something else: a temporary overlay can exist over the external stones, without need for reduced board and stones.

**Comment by popz73** [comment]
of course. The example above from the Pandanet app has the same restrictions and I like their implementation, the compromise is reasonable. (an opposite example: BW-Go's coordinate implementation are much sloppier, taking way too much space).

There are two different use cases: 

- a setting to have the coordinates visible or not by default (the toggle I'm describing above)

- a way to have a quick glance at the coordinates, to be able to refer to a move occasionally without needing to switch the setting on/off
This one doesn't merit a setting/button taking space on the game area, has to be something intuitive - I'm thinking long-press ( >1s ) anywhere on the board to display a coordinates overlay, that goes away when depressed.

I can take care of both changes if @acristescu is fine with the idea - would probably even start by the overlay one (it's the one I'd be using) :)

**Comment by heikoherold** [comment]
Ah, nice. I understand now, basically this is (could be) the difference between large screen devices e.  g.  tablets, and small screen devices like phones (or large screen devices for people with vision difficulties).

**Comment by heikoherold** [comment]
Ah, I understand the point. Put the info in the Menu? I mean, have a three-way menu point toggling between:
- Show coordinates always
- Show coordinates on long press on border
- Show coordinates never
?
Argh, I'm no Ux designer either, sorry

**Comment by acristescu** [comment]
I think we should start by having a 2-way toggle in both the game menu and the global settings (they would be both backed by the same variable so they would be in sync). A second feature would be to add another 2-way toggle inside the global settings alone that enables/disables "glancing" at coordinates by doing some hidden combo (e.g. long-press something). This way the user has a chance of discovering the feature by reading about it in the global settings.

**Comment by popz73** [comment]
I'm taking care of the first feature (the synced toggle in the settings and menu is done, but it'll take me some time to get the board right)

**Comment by acristescu** [comment]
I agree that's the trickiest part of this feature. The board is the oldest part of the code, started with it over 4 years ago and it was written in Java and later converted to Kotlin. It's so old that it was initially written in eclipse not Android Studio.

I could maybe do that, not sure when I will find the time to do it though...

**Comment by popz73** [comment]
starts to look good, I'm almost finished, should have a PR ready by next week.
(you can assign this one to me if you wish - I can't assign items)
preview:
<img src="https://user-images.githubusercontent.com/12851952/50578202-bccbb380-0e36-11e9-89e1-94520245f1fe.png" width="400">

**Comment by acristescu** [comment]
Thank you for taking a look at it. Github won't let me assign the issue to you either for whatever reason (?) but it's safe to assume nobody else is going to pick it up since only you and me are contributing :)

**Comment by acristescu** [comment]
Merged in `alpha_b186`
