### ISSUE TITLE
Issues with time left info

### ISSUE THREAD

**Issue by goffreder** [acristescu/OnlineGo#39]
For some games, the time left information is wrong, both in the games list view and in the game view. See attached screenshots:
![screenshot_20181230-193433](https://user-images.githubusercontent.com/156642/50550228-9bb76700-0c6c-11e9-8dee-2362b90df0b9.png)
![screenshot_20181230-193839](https://user-images.githubusercontent.com/156642/50550229-9bb76700-0c6c-11e9-9bf3-4f7f84741dbf.png)
![screenshot_20181230-193842](https://user-images.githubusercontent.com/156642/50550230-9c4ffd80-0c6c-11e9-8a11-c68d6369008b.png)

The games are:
https://online-go.com/game/15872226
https://online-go.com/game/15910341

Also, for game #15872226 the counter is continuously decreasing in the game view.

**Comment by acristescu** [comment]
Thank you for the report, I'll have a look

**Comment by acristescu** [comment]
Fixed in the next version (at least for second game since the first is private). Fix will be available in the next version (168+)
