### ISSUE TITLE
Ability to open a game in the browser

### ISSUE THREAD

**Issue by popz73** [acristescu/OnlineGo#49]
Hi Alex, having a way to open the game in the browser would be useful.
Was it a choice not to do it? Given the gap between app and website functionality (conditional moves, Malkovich comments, etc..), I think it would make total sense, at least for the time being.

As an example, if you're familiar with BW-Go and its plugin to play correspondence games on DGS, a similar "browse to game" option in the contextual menu would suffice. I can do a PR with it if you're OK.

**Comment by acristescu** [comment]
Damn, I just saw this now :) Sure, if you're still up for it after 8 months, I don't see why not...
