### ISSUE TITLE
Contributing assistance

### ISSUE THREAD

**Issue by TheIronMarx** [acristescu/OnlineGo#51]
Hello!

I'm trying to get this project up and running so I can contribute to the project and tackle some tasks, but out of the box Gradle sync and building both have issues. Would you kindly introduce a write up on how an individual without your google-services.json, etc. can contribute to this project?

**Comment by TheIronMarx** [comment]
After simply commenting out google-services and fabric from the `build.gradle`s, Crashlytics is the next problematic bit. Perhaps there are dummy, non-prod values that can be introduced and then replaced when you publish?

**Comment by TheIronMarx** [comment]
I see you pushed some new work a few days ago. Happy to see it! 

I'd love to help contribute, man, but the Crashlytics and Google Services is clipping my wings. Maybe if I wrapped it around a debug check from `BuildConfig`, and didn't call that when it was debug mode, that might work. But I'm not sure auth would function then? 

If nothing, I'm going to fork the project and not PR back up :\

**Comment by acristescu** [comment]
Hey man, sorry I've been a bit busy with my private life. I just pushed some work I've done recently. Hopefully the time I can devote this project will increase after new year's eve.

For the issues you're encountering: I don't think Crashlytics is actually a problem as it will not crash the build (just not report, right?). As for google services, you just need to provide another google-services.json file with another project id. Other people have done it, perhaps they can provide some hints of what they did (for example @popz73 comes to mind).

I like your idea of maybe including a debug google services in the repo and inject the real one using the CI machine (as I am doing right now). When I find time, I will try pulling the code on a new laptop and see what problems I encounter, but not sure when I can find the time to do that. Sorry I cannot provide more assistance right now.

**Comment by TheIronMarx** [comment]
If I'm remembering correctly, I believe it Crashlytics was crashing on init and logs when I commented out the init.

If there needs to be a google-services.json that's fine, let's commit one to the repo. The CI server you use can swap it out for the real deal when you publish.

**Comment by popz73** [comment]
Hi, indeed I had no problem setting up the repo to work on it some months
back. Don't think the configuration has changed since.. I'll have a look in
the weekend

**Comment by popz73** [comment]
hi @TheIronMarx ,
doesn't help much, but now that I finally got to resume contributions, adding my own google-services.json was the only thing I remember needing.

**Comment by acristescu** [comment]
I can confirm in the meantime I have pulled this on my new laptop and all I had to plug in were the `googe-services.json`. It would still be good if somebody would find the time to provide a short description of how to do it...

**Comment by cyberatlas** [comment]
Hi @TheIronMarx I can confirm your issue. I ran into the same errors. The issues with Crashlytics are dependent on how you handle the first issues regarding the `google-services.json` file. From what I understand they solved the issue by generating the file through personal Google accounts with Firebase (please correct me if I am wrong). 

I took the same approach you did and decided to try commenting it out. I commented out the following line which allowed the build to proceed.

https://github.com/acristescu/OnlineGo/blob/20df4cb0ebe0627c2b13cdfdb14b90b302e3462c/app/build.gradle#L6

Then an error arose with the Crashlytics API key being null. I was able to get past that issue by adding the following to `app/src/main/AndroidManifest.xml`:

```
<meta-data android:name="io.fabric.ApiKey"
android:value="0" />
```
From there the app was able to successfully build, pass all tests, and open a login screen on my phone. I have not gotten a chance to test any further. I am not sure if it will let you log in or not. I am also not really sure if there is a way to test the app without having  to login each time. Perhaps @acristescu or @popz73 will have some further insight into this. 

It is worth noting that fabric.io was bought by Google and integrated into Firebase. I suspect that by solving the first issue they got the necessary access to Crashlytics - thus not being able to reproduce the error. 

This is all new to me, but time permitting I will play with it more and try to find a less hacky solution. It's likely that the Firebase connection is necessary and commenting it out simply won't work. Regardless of how the dev environment must be set up, I will create documentation around this.

Any guidance or advice would be appreciated.

**Comment by cyberatlas** [comment]
My previous idea for disabling the requirements did not work. The app successfully built, but nothing actually worked. I have made a PR with a guide on creating on the `google-services.json` file. Once that is done everything builds and runs properly.

**Comment by MathieuDreano** [comment]
If that might help some of you.
I had to do the following changes

- create a google-service.json file (added a readme for this)
- change Gradle version (build.gradle root)
- change CMake version (build.gradle app)

**Comment by benjaminpjones** [comment]
@MathieuDreano this helped.  I did some similar remedies:

- Added `google-service.json` as described in CONTRIBUTING.md
- Changed Gradle Plugin version to the 7.4.1 (I think this is the default for Android Studio Electric Eel)
    - I wondered if @acristescu  is on one of the [preview versions of Android Studio](https://developer.android.com/studio/preview)? But I tried Flamingo (Beta) and Giraffe (Canary) without much luck
- Used SDK Manager to download CMake 3.10.2

*File > Project Structure*:
<img width="447" alt="Screen Shot 2023-02-12 at 3 14 06 PM" src="https://user-images.githubusercontent.com/25233703/218296511-125bbafc-0de8-4e6b-aa1b-330faa017ec7.png">
*Tools > SDK Manager > SDK Tools*:
<img width="195" alt="Screen Shot 2023-02-12 at 3 14 38 PM" src="https://user-images.githubusercontent.com/25233703/218296503-9b318217-02ac-488f-8dc0-89e0a38febf5.png">

**Comment by acristescu** [comment]
Indeed, I am on Canary (which is giraffe I think?). Heck I use Canary even at work, it's quite stable. Feel free to use whatever version you'd like of course, but then, as noted, you need to downgrade your AGP to match. It's just the way it is with Android development.

PS: 8.0 is for Flamingo, 8.1 is for Giraffe.

For CMake I do not recommend bumping the version, but instead installing the old NDK that the project requires. Should matter much if you don't go into the score estimator.

**Comment by clementcontet** [comment]
Hi, I'm trying to build and run the app on my phone.
It works fine until I have to log-in, I always get `signInResult:failed code=10` when trying with my Google account.
Is there something I have to set on the Firebase project?

**Comment by acristescu** [comment]
Hi, @clementcontet Google sign-in depends on the app being signed with the official signing key. This is because the key is whitelisted by Anoek in the OGS Google profile. Sadly I can't make that public (as whoever has it can fake the app on Google Play), so any development work will have to take place with a username and password.

**Comment by bqv** [comment]
I'm unsure if using debug builds is part of your process, but I notice that in a debug build the websocket is so chatty that it lags out and disconnects repeatedly

**Comment by acristescu** [comment]
> I'm unsure if using debug builds is part of your process, but I notice that in a debug build the websocket is so chatty that it lags out and disconnects repeatedly

That's weird... I'm using a debug build almost daily on my phone and I didn't have any issues. I do not see why the websocket would behave differently between a debug and a release build.

The only time where I encountered this was for Sofia who had in excess of 1200 simultaneous games. This was a problem for both live and debug builds. How many games do you have?

**Comment by bqv** [comment]
No more than 10 active games at any time. Maybe this is me, somehow - I'll do some more digging

**Comment by acristescu** [comment]
@bqv could this be it? https://forums.online-go.com/t/lost-by-erroneous-time-out/49243/8?u=teapoweredrobot

**Comment by bqv** [comment]
Unlikely, it happens even with no games playing, apparently, so I think something deeper is up, but i've yet to suss out the actual cause

**Comment by bqv** [comment]
Solved, it was due to the notification permission missing on the debug installation. Nothing to worry about :)
