### ISSUE TITLE
Chip dialogs are only displayed on one game per session

### ISSUE THREAD

**Issue by popz73** [acristescu/OnlineGo#63]
Noticed this when doing the dark theme.. easily reproducible on the base app

- Open app (list of games)
- Open a game from the list
- Click the "playing" chip - dialog is shown
- Go back to the list of games
- Open another game
- Click the "playing chip" - nothing happens

**Comment by acristescu** [comment]
They say you're not a real android developer unless you've leaked the context at least once. Proud to still be doing this rookie mistake in 2020 :)

Fixed in the next version.
