### ISSUE TITLE
Wrong color after undo

### ISSUE THREAD

**Issue by gaffney2010** [acristescu/OnlineGo#64]
I've found that after accepting the opponent's undo, when they play a new piece, that piece appears in my color.

**Comment by acristescu** [comment]
Thanks for the report, I will try to see what's going on. As a workaround for this sort of situations refreshing the game (by going out of it and back into it) should fix the issue for now.

**Comment by acristescu** [comment]
I re-implemented the undo accepted stuff with a (hopefully) more robust method. Should work every time in the next version (will probably be released tomorrow).
