### ISSUE TITLE
undo notification stuck

### ISSUE THREAD

**Issue by alexmitrani** [acristescu/OnlineGo#68]
My opponent requested undo and resigned before I got the notification.  The notification is now stuck, it pops up every time I open the game. 

![Screenshot_20200721-102522](https://user-images.githubusercontent.com/27974470/88067325-d9c0f800-cb3c-11ea-9a6c-cbc2d4cb49e3.png)

Please fix so that any undo request notification should only show once or not at all, when the game has ended.   

Thanks. 

P.S. This is the game: https://online-go.com/game/25561488

**Comment by acristescu** [comment]
The rewrite should have fixed this.
