### ISSUE TITLE
Feature request: more detailed units for time remaining

### ISSUE THREAD

**Issue by alexmitrani** [acristescu/OnlineGo#72]
Please could we have a small tweak to how remaining time is displayed? For ladder games (increment measured in days) Xd Yh for durations > 1 day, not just Xd like now.

More generally, I think the principle should be to show duration measured in two units: the main unit of interest and the next smaller unit. So if the increments are in weeks, show Xw Yd. Does that make sense?

Thanks.

**Comment by DrewHeath** [comment]
I strongly support this request. As currently designed, the time remaining is almost useless for fast correspondence games.

As an example, here is my current dashboard:

    Opponent    App Time Left    Web Time Left    
    toferi    1 day    25 hours
    lojastygm    1 day    28 hours
    mlopezviedma    1 day    29 hours
    Boben    1 day    29 hours
    DouglasB    1 day    31 hours
    Iridium    1 day    38 hours
    S_Alexander    1 day    41 hours

There is a very big difference between 25 and 41 hours, and neither of them are 1 day!!!
I suggest that the application switch to an "hours remaining" display once the time remaining is less than 48 hours 00 minutes.

**Comment by DrewHeath** [comment]
![Screenshot_20201209-172721_Online Go](https://user-images.githubusercontent.com/5154248/101701166-faceaa80-3a43-11eb-9d5c-33976dbb2f82.jpg)

**Comment by acristescu** [comment]
The relevant code right now is:

```fun formatMillis(millis: Long): String {
    var seconds = ceil((millis - 1) / 1000.0).toLong()
    val days = seconds / 86_400
    seconds -= days * 86_400
    val hours = seconds / 3_600
    seconds -= hours * 3_600
    val minutes = seconds / 60
    seconds -= minutes * 60

    return when {
        days >= 7 -> "%d week%s".format(days / 7, plural(days / 7))
        days > 0 -> "%d day%s".format(days, plural(days))
        hours > 0 -> "%dh %02dm".format(hours, minutes)
        minutes > 0 -> "%d : %02d".format(minutes, seconds)
        seconds > 10 -> "%02ds".format(seconds)
        millis > 0 -> "%.1fs".format(millis / 1000f)
        else -> "0.0"
    }
}```

Could you guys suggest exact thresholds and formats?

**Comment by alexmitrani** [comment]
I don't understand the details of the code but I do get the gist.  

This line "hours > 0 -> "%dh %02dm".format(hours, minutes)" already does what is needed for durations of less than a day and more than an hour.  This is fine.  

It just needs extending in a similar way for durations of more than a day and more than a week, these lines:

days >= 7 -> "%d week%s".format(days / 7, plural(days / 7))
        days > 0 -> "%d day%s".format(days, plural(days))

In the line "days >= 7 -> "%d week%s".format(days / 7, plural(days / 7))" something needs adding to display the result in weeks and days: "W weeks, D days".  

Similarly, in the line "days > 0 -> "%d day%s".format(days, plural(days))" a change is needed to show the duration like "D days, H hours".  

In each case the quantity of time measured in the  smaller unit will be the difference between the total duration in that unit and the duration represented by the integer quantity of the larger unit.  

For instance if there are 45 hours left
Presently this is displayed as 1 day.  
With the desired functionality it would be displayed as 1 day, 21 hours.
This is more a bug fix than an enhancement: rounding 45 hours down to 1 day is an error of 47%.  

I think you can keep the existing thresholds.

I hope this helps.  

Thanks

**Comment by v011** [comment]
Hi @acristescu , @alexmitrani , please have a look at the pull request.

Thanks

**Comment by alexmitrani** [comment]
Hi @v011, I am unable to comment on the details of the code, but if it works as stated that will be a big improvement.  Many thanks.

**Comment by v011** [comment]
@alexmitrani , yes, the code works as stated. I've suggested, in the pull request, an alternative format which seems to be more suitable for small screens.
