### ISSUE TITLE
Learning mode using KataGo

### ISSUE THREAD

**Issue by bkhl** [acristescu/OnlineGo#77]
For new players picking up the game I often recommend playing 9x9 against http://www.smart-games.com/igowin.html, which starts with a five stone handicap and automatically adjusts it up once the player beats it a few times at a given handicap.

From now on I'll probably recommend doing the same with Online Go+Katago instead, as an Android app is a lower barrier for most people than downloading a Windows application these days. However, it takes a bit of explaining of handicaps and things to get them to get the idea at the moment.

So, a nice addition here I think would be a mode like that, maybe as a new option in the "Learn" tab?

**Comment by acristescu** [comment]
That's not a bad idea, we could have a "progressive" or "auto" setting for the handicap. Although as you say this will prove confusing as hell for new players (precisely the people who would benefit from this) if not properly explained...

**Comment by bkhl** [comment]
Well, if it's automated it seems at least easier to explain and let them pick it up on their own, than if you have to tell them to gradually adjust the handicap themselves.

Maybe this could be the final stages of the tutorial (#18), with each new easier level being presented as a stage.

A beginner will probably have to play for a long time until they play even with Katago on 9x9, though, so it might be best to finish it when they beat it at three stones or so, and say that by then they are probably ready to meet other players online in 9x9.
