### ISSUE TITLE
AI is stuck (Invalid KO moves are allowed)

### ISSUE THREAD

**Issue by amunizp** [acristescu/OnlineGo#79]
![Screenshot_2020-11-03-09-04-33-446_io zenandroid onlinego](https://user-images.githubusercontent.com/5783911/98421140-9acd9880-2080-11eb-8a66-2dd9babc18bb.jpg)

Clicking Territory and Hint change the message from "I'm thinking..." To  "OK, calculating current territory..." And "Hmm...".

How long does the Offline AI take to pass? If I move to another app or shut down the app, does it forget what it managed to think so far and is able to pick up where it left off?

**Comment by acristescu** [comment]
There is a bug in that the AI doesn't really tell you it has passed. If it says it's your turn without making a move, then it passed... Sorry, I need to fix that.

**Comment by amunizp** [comment]
It is stuck on "I'm thinking and does not let me position  my piece.

**Comment by acristescu** [comment]
Hmm that is very interesting. I need to improve the reporting of problems. It seems here that there might be a bug with the interpretation of the KO rule. I think my app uses super-ko while KataGo (correctly) uses simple japanese ko rules.  Am I right in assuming the last few moves where related to the KO fight around F9 and G9? Can you please provide your OGS username and the last few moves in the position?

**Comment by amunizp** [comment]
My last move was F9 and I do believe the fight was there.

The app does not let me go back moves as I am effectively stuck on the AI move.

But my user name is the same as here amunizp

**Comment by acristescu** [comment]
Ah, yes, I found the error report on crashlytics. It is indeed related to KO rules interpretation, as katago thinks the F9 move is illegal.

The only way to get it unstuck I'm afraid is to delete the app data, but you will have to log in again. On most phones you can do this by long pressing the app icon -> app info -> storage -> clear data. Not sure how it is on the Redmi. Sorry about that.

For the record:

```KATAGO> {"id":"1","moves":[["B","C7"],["W","F4"],["B","G3"],["W","D6"],["B","E5"],["W","G4"],["B","H4"],["W","F6"],["B","E4"],["W","E6"],["B","F3"],["W","C6"],["B","H5"],["W","B5"],["B","G6"],["W","C3"],["B","F7"],["W","E8"],["B","F5"],["W","F8"],["B","G5"],["W","E2"],["B","G8"],["W","F1"],["B","F9"],["W","E9"],["B","H9"],["W","G7"],["B","H7"],["W","D3"],["B","C4"],["W","C8"],["B","C5"],["W","B4"],["B","B6"],["W","A6"],["B","B7"],["W","D8"],["B","D7"],["W","E7"],["B","D4"],["W","G9"],["B","B8"],["W","C9"],["B","B9"],["W","A7"],["B","F9"],["W","G7"],["B","D5"],["W","F2"],["B","F7"],["W","G9"],["B","F9"]],"initialStones":[],"rules":"japanese","komi":5.5,"boardXSize":9,"boardYSize":9,"maxVisits":20,"includeOwnership":true,"includeMovesOwnership":true}

Katago: {"error":"Illegal move 52: F9","field":"moves","id":"1"}
io.zenandroid.onlinego.ai.KataGoAnalysisEngine$startEngine$2$2.run (KataGoAnalysisEngine.kt:79)
```

Thank you for the report, I will have to fix this.

**Comment by amunizp** [comment]
Cleared data as you said an played again. I had a couple of exchanges of KO movements.

![Screenshot_2020-11-08-14-56-24-733_io zenandroid onlinego](https://user-images.githubusercontent.com/5783911/98468553-e728ed80-21d2-11eb-9afb-485aa39e0d59.jpg)

I am just learning go but I think the gist of what you are saying is correct.

**Comment by acristescu** [comment]
Yes, it's definitely that I'm not detecting KO correctly. Sorry, I imagine this would be quite confusing for a new player. I will fix it in the next release. In the meantime, try to avoid to play a move that immediately repeats the position (like the F9-G9-F9-G9-F9-G9 exchange in the first game)

**Comment by acristescu** [comment]
Fixed
