### ISSUE TITLE
Better finished game UI

### ISSUE THREAD

**Issue by acristescu** [acristescu/OnlineGo#9]

**Comment by acristescu** [comment]
Partially implemented in v145. Still pending:

- Proper "you win/lose" dialog with score where applicable
- Display a "resigned" or "timed out" chip for the user that lost if the game didn't end in scoring

**Comment by Kiolk** [comment]
Hi, folks. Is this issue actual to implement? Do you have specific design for this dialog?

**Comment by acristescu** [comment]
Hi @Kiolk,

It is indeed actual, and I the only designs I have (see below) are more wireframes than anything. At the very least they should show the score calculations, as the beginners in particular fail to understand who won and why (I get emails about it).

![image](https://user-images.githubusercontent.com/2835035/96307430-83f3d300-0ff9-11eb-8f8f-bab0a731b1ce.png)

Should you want to take this on, I would start with proposing a design.

**Comment by acristescu** [comment]
Implemented as part of the rewrite.
