### ISSUE TITLE
No notifications after last update

### ISSUE THREAD

**Issue by jnkstry** [acristescu/OnlineGo#98]
I am sorry to bother you. After the Last update i dont get notifications at all. I have to enter the app to see in which games it is my turn. Is it just me?
I have a Xiaomi Mi9T and it is running on Android 11. Already tried deleting cache, restart of phone and also re-installed the app.
Before the update i did get notifications but als for some finished games but that got fixed with the latest update.

**Comment by popz73** [comment]
I confirm this, on my end I also completely stopped receiving notifications

**Comment by acristescu** [comment]
Arf... beginner mistake by my part, I fixed it and will release as soon as possible. Thank you for the report @jnkstry and @popz73
